name: Hallo Github actions

on:
  push:
    branches:
      - main
      
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print een bericht
        run: echo "Hallo Github actions"
